project:
  type: website

website:
  title: "Victor .O. Oseji"
  page-navigation: true
  google-analytics: " "
  open-graph: true
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - icon: house-door-fill
        text: Home
        href: index.qmd
      - icon: person-lines-fill
        text: About Me
        href: about.qmd
      - icon: file-bar-graph-fill
        text: Portfolio
        href: projects.qmd
      - icon: chat-square-fill
        text: Blog
        href: blog.qmd
      - icon: envelope-fill
        text: Resume
        href: resume.qmd
    right:
      - icon: github
        href: https://github.com/oseji9827
      - icon: twitter
        href: https://twitter.com
    pinned: true
    collapse: true
  page-footer: 
    background: "#373737"
    left: "© Copyright 2023 Victor Oseji."
    center: ""
    right:
      - icon: github
        href: https://github.com/oseji9827
      - icon: linkedin
        href: https://linkedin.com/victor-oseji-50243663
      - icon: envelope
        href: mailto:jeremjiose@gmail.com
format:
  html:
    smooth-scroll: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    grid:
      sidebar-width: 0px
      body-width: 1300px
      margin-width: 0px

editor: visual

execute:
  freeze: auto

